{
  type:"pageview",
  root:["header","body"],
  style:{"backgroundColor":"#fff"},
  components:{
    header:{
      type:"header",
      root:["退出","headersegment","headerempty"],
      style:{
        height:52,
        justifyContent:"space-between",
        alignItems:"center",
        backgroundColor:"rgb(18,181,242)"
      }
    },
    headerempty:{
      type:"view",
      style:{
        width:50
      }
    },
    headersegment:{
      type:"segment",
      styletype:"2",
      items:["商品","详情","评价"],
      style:{
        width:150,
        marginTop:4
      },
      itemStyle:{
        ios_height:38,
        android_height:48,
        web_height:48,
      },
      textStyle:{
        fontSize:15
      },
      selectedTextStyle:{
        color:"black",
        fontSize:15
      },
      indicatorStyle:{
        backgroundColor:"black"
      }
    },
    退出:{
      type:"icon",
      icon:"e960",
      style:{width:50,height:44,justifyContent:"flex-start",paddingLeft:5},
      iconStyle:{color:"#fff",fontSize:18}
    },
    body:{
      type:"view",
      overflow:"auto",
      style:{
        paddingTop:10,
        flex:1
      },
      root:[
        "DemoButton"
      ]
    },
    DemoButton:{
      type:"button",
      text:"点击就送屠龙刀",
      style:{
        backgroundColor:"rgb(255,42,95)",
        width:200,
        paddingTop:10,
        paddingBottom:10,
        borderRadius:20,
        overflow:"hidden"
      },
      textStyle:{
        textAlign:"center",
        color:"#fff",
        fontSize:14,
      }
    },
  }
}
